version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/setup_environment.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/delete_default_index.sh    # Deletes /var/www/html/index.html
      timeout: 60
      runas: root
    - location: scripts/set_permissions.sh
      timeout: 120
      runas: root
    - location: scripts/configure_wp.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 60
      runas: root

