version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      # Update package list and install git
      - echo "Updating apt and installing git"
      - apt-get update
      - apt-get install -y git

  pre_build:
    commands:
      # Clone the GitHub repository
      - echo "Cloning WordPress repository from GitHub"
      - git clone https://github.com/Anas154/wordpress.git

  build:
    commands:
      # Navigate to the WordPress directory
      - echo "Navigating to the wordpress directory"
      - cd wordpress/wordpress

      # Create a tar.gz file
      - echo "Creating tar file"
      - tar -czf wordpress.tar.gz .

  post_build:
    commands:
      # Move the tar to a known location (since we're deep inside directory)
      - echo "Moving tar file to /tmp for upload"
      - mv wordpress.tar.gz /tmp/

      # Upload to S3
      - echo "Uploading tar file to S3 bucket"
      - aws s3 cp /tmp/wordpress.tar.gz s3://build-wordpress28/wordpress.tar.gz

artifacts:
  files:
    - /tmp/wordpress.tar.gz

