version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Using default dependencies available in CodeBuild image"
      - git --version
      - curl --version
      - aws --version

  pre_build:
    commands:
      - echo "Testing internet access"
      - curl -I https://github.com || echo "Internet access failed"
      - echo "Cloning WordPress repo"
      - git clone https://github.com/Anas154/wordpress.git wordpress-src

  build:
    commands:
      - echo "Creating deployment package with WordPress files"
      - mkdir -p package
      - cp -r wordpress-src/wordpress/* package/
      - cp wordpress-src/appspec.yml package/
      - cp -r wordpress-src/scripts package/
      - tar -czf wordpress_deploy_package.tar.gz -C package .

  post_build:
    commands:
      - echo "Uploading package to S3"
      - aws s3 cp wordpress_deploy_package.tar.gz s3://anas-101/wordpress_deploy_package.tar.gz

artifacts:
  files:
    - wordpress_deploy_package.tar.gz

