version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
      - apt-get update && apt-get install -y git curl

  pre_build:
    commands:
      - echo "Testing internet access"
      - curl -I https://github.com || echo "Internet not working"

      - echo "Cloning repo"
      - cd /tmp
      - rm -rf wordpress || true
      - git clone https://github.com/Anas154/wordpress.git

  build:
    commands:
      - echo "Creating tar file"
      - cd /tmp/wordpress/wordpress
      - tar -czf wordpress.tar.gz .
      - mv wordpress.tar.gz /tmp/

  post_build:
    commands:
      - echo "Uploading to S3"
      - aws s3 cp /tmp/wordpress.tar.gz s3://build-wordpress28/wordpress.tar.gz

artifacts:
  files:
    - /tmp/wordpress.tar.gz

