version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y git curl

  pre_build:
    commands:
      - echo "Testing internet access"
      - curl -I https://github.com || echo "Internet access failed"

      - echo "Cloning WordPress repo"
      - cd /tmp
      - rm -rf wordpress || true
      - git clone https://github.com/Anas154/wordpress.git

  build:
    commands:
      - echo "Creating tar file from /tmp/wordpress/wordpress"
      - cd /tmp/wordpress/wordpress
      - tar -czf /tmp/wordpress.tar.gz .

  post_build:
    commands:
      - echo "Uploading tar file to S3"
      - aws s3 cp /tmp/wordpress.tar.gz s3://build-wordpress28/wordpress.tar.gz

artifacts:
  files:
    - /tmp/wordpress.tar.gz

